### ISSUE TITLE
`url_for` error in Trailblazer::Cell - Cell::ViewModel works fine

### ISSUE THREAD

**Issue by ziyan-junaideen** [trailblazer/trailblazer-cells#14]
I started trying out `cells` in when I started the project. I liked what I saw. Then I thought of giving `trailblazer` as a whole a test run. I copied the cell and view to the trailblazer file structure and changed the namespace.

That is when I noticed there was an error w.r.t. `url_for`.

The particular error I am getting is when accessing ActiveStorage image URL. But it is not limited to such. Even getting a controller action gives the same error `url_for controller: 'marketing/services', action: 'index'`. This doesn't happen when I use `cell-rails` stand alone which is why I created the issue here. I checked out the cells `url_for` implementation. I understand the pain, but that doesn't seem to be the case since `cells-rails` `url_for` works else where.

```
Started GET "/" for 192.168.10.1 at 2021-04-05 11:00:44 +0000
Cannot render console from 192.168.10.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by PagesController#home as HTML
  Rendering layout layouts/application.html.erb
  Rendering pages/home.html.erb within layouts/application
  Rendered pages/home/_main_slider.html.erb (Duration: 0.4ms | Allocations: 107)
  Rendered pages/home/_passion.html.erb (Duration: 2.0ms | Allocations: 813)
  Service Load (0.7ms)  SELECT "services".* FROM "services" WHERE "services"."name" = $1 LIMIT $2  [["name", "Wash & Fold"], ["LIMIT", 1]]
  ↳ app/views/pages/home/_services.html.erb:42
  ActiveStorage::Attachment Load (1.1ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Service"], ["name", "slick_background"], ["LIMIT", 1]]
  ↳ app/concepts/service/cell/slick_item.rb:24:in `slick_background_image'
  ActiveStorage::Blob Load (0.9ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/concepts/service/cell/slick_item.rb:24:in `slick_background_image'
  Rendered pages/home/_services.html.erb (Duration: 12.1ms | Allocations: 11616)
  Rendered pages/home.html.erb within layouts/application (Duration: 17.4ms | Allocations: 13410)
  Rendered layout layouts/application.html.erb (Duration: 17.9ms | Allocations: 13475)
Completed 500 Internal Server Error in 22ms (ActiveRecord: 2.7ms | Allocations: 15220)



ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    39:           }
    40:         ]
    41:       }'>
    42:         <%= Service::Cell::SlickItem.new(Service.find_by_name('Wash & Fold')).() %>
    43:
    44:         <%= cell(:service, Service.find_by_name('Wash & Fold')).(:slick_item) %>
    45:

app/concepts/service/cell/slick_item.rb:24:in `slick_background_image'
app/concepts/service/view/slick_item.slim:4:in `block in __tilt_33800'
app/concepts/service/view/slick_item.slim:2:in `__tilt_33800'
app/concepts/service/cell/slick_item.rb:15:in `show'
app/views/pages/home/_services.html.erb:42
app/views/pages/home.html.erb:7
```

## Implementation

I have some thing like this

* Gemfile

```rb
gem 'trailblazer-rails'
gem 'dry-validation'
gem 'reform-rails'
gem 'trailblazer-cells'
gem 'cells-rails'
gem 'cells-erb'
gem 'cells-slim'
```

* Initialiser

```rb
LaundryRails::Application.config.trailblazer.enable_loader = false
LaundryRails::Application.config.reform.validations = :dry

require "trailblazer/developer"
Dev = Trailblazer::Developer
```

* Trailblazer::Cell

```rb
# app/concepts/service/cell/slick_item.rb
module Service::Cell
  class SlickItem < Trailblazer::Cell
    include ::Cell::Slim

    property :id
    property :name

    property :slick_title
    property :slick_description
    property :slick_icon
    property :slick_svg
    property :slick_background

    def show
      render
    end

    def slick_unified_icon
      return slick_svg if slick_svg
      return content_tag(:i, '', class: slick_icon) if slick_icon
    end

    def slick_background_image
      image_tag url_for slick_background.variant(resize_to_fit: [600,520])
    end
  end
end
```

* Cell::ViewModel

```rb
# app/cell/service_cell.rb

class ServiceCell < Cell::ViewModel
  include ::Cell::Slim

  property :id
  property :name

  property :slick_title
  property :slick_description
  property :slick_icon
  property :slick_svg
  property :slick_background

  def slick_unified_icon
    return slick_svg if slick_svg
    return content_tag(:i, '', class: slick_icon) if slick_icon
  end

  def slick_background_image
    image_tag url_for slick_background.variant(resize_to_fit: [600,520])
  end

  def slick_item
    render
  end

  def image_box
    render
  end
end
```

**Comment by apotonick** [comment]
Hi, you're using the wrong mechanics to render your cells, I guess. You're invoking the private mechanism `Cell.new.()`, but it should be the `cell` helper: http://trailblazer.to/2.1/docs/cells.html#cells-trailblazer-invocation Make sure you're using `Trailblazer::Cell`, as we will remove the older `Cell::Rails` and `Cell::Concept` in the future. :beers:

**Comment by ziyan-junaideen** [comment]
Oh my... it was the case...
I was pretty sure I tried that last night but was very tired...
When it didn't work I even restarted vagrant...
May be I didn't save...
Tried a variety of ways, just in case...
Silly me

Sorry about that...
Thanks for the help! Thanks for the info.
Great stuff Nick!

**Comment by apotonick** [comment]
Always a pleasure, @ziyan-junaideen!
